module.exports = function (migration) {
  // deprecate slugs now that they're being autogenerated
  function deprecateSlug(type) {
    const contentType = migration.editContentType(type);
    contentType
      .editField('slug')
      .name('Slug (deprecated)')
      .disabled(true);
    contentType.moveField('slug').toTheBottom();
  }
  [
    'supportedLanguages',
    'comparisonTable',
    'expansion',
    'productDetail.SystemRequirements',
    'gameDetails',
    'faqContainer',
    'pdpLayoutNewsArticles',
    'screenShotsVideos'
  ].map(deprecateSlug);
};
