name: Integration

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: 'Prepare integration'
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.T2GP_BUILD_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: take-two
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-${{ env.cache-name }}-
            ${{ runner.OS }}-npm-
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.T2GP_BUILD_TOKEN}}
      - name: Lint
        run: npm run lint
      - name: Cleanup existing environment
        run: npm run ci:cleanup
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          CONTENTFUL_DELIVERY_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_ACCESS_TOKEN }}
          ENVIRONMENT_ID: ${{ github.head_ref }}
      - name: Prepare environment
        run: npm run ci:prepare
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          CONTENTFUL_DELIVERY_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_ACCESS_TOKEN }}
          ENVIRONMENT_ID: ${{ github.head_ref }}
      - name: Danger checks
        run: npm run ci:danger
        env:
          GITHUB_TOKEN: ${{ secrets.T2GP_BUILD_TOKEN }}
